const opdList = [
    "BADAN KEPEGAWAIAN DAERAH",
    "BADAN KESATUAN BANGSA DAN POLITIK",
    "BADAN PENGELOLA KEUANGAN DAN ASET DAERAH",
    "BADAN PENGELOLA PENDAPATAN DAERAH",
    "BADAN PENGEMBANGAN SUMBER DAYA MANUSIA DAERAH",
    "BADAN PENGHUBUNG",
    "BADAN PERENCANAAN PEMBANGUNAN DAERAH",
    "BADAN RISET DAN INOVASI DAERAH",
    "BIRO ADMINISTRASI PEMBANGUNAN DAERAH",
    "BIRO ADMINISTRASI PENGADAAN BARANG/JASA",
    "BIRO HUKUM",
    "BIRO INFRASTRUKTUR DAN SUMBER DAYA ALAM",
    "BIRO KESEJAHTERAAN RAKYAT",
    "BIRO ORGANISASI",
    "BIRO PEMERINTAHAN, OTONOMI DAERAH DAN KERJASAMA",
    "BIRO PEREKONOMIAN",
    "BIRO UMUM",
    "DINAS ENERGI DAN SUMBER DAYA MINERAL",
    "DINAS KEARSIPAN DAN PERPUSTAKAAN",
    "DINAS KELAUTAN DAN PERIKANAN",
    "DINAS KEPEMUDAAN, OLAHRAGA DAN PARIWISATA",
    "DINAS KESEHATAN",
    "DINAS KETAHANAN PANGAN",
    "DINAS KOMUNIKASI DAN INFORMATIKA",
    "DINAS KOPERASI, USAHA KECIL DAN MENENGAH",
    "DINAS LINGKUNGAN HIDUP DAN KEHUTANAN",
    "DINAS PEKERJAAN UMUM BINA MARGA DAN CIPTA KARYA",
    "DINAS PEKERJAAN UMUM SUMBER DAYA AIR DAN PENATAAN RUANG",
    "DINAS PEMBERDAYAAN MASYARAKAT, DESA, KEPENDUDUKAN DAN PENCATATAN SIPIL",
    "DINAS PEMBERDAYAAN PEREMPUAN, PERLINDUNGAN ANAK, PENGENDALIAN PENDUDUK DAN KELUARGA BERENCANA",
    "DINAS PENANAMAN MODAL DAN PELAYANAN TERPADU SATU PINTU",
    "DINAS PENANAMAN MODAL DAN PELAYANAN TERPADU SATU PINTU",
    "DINAS PENDIDIKAN DAN KEBUDAYAAN",
    "DINAS PERHUBUNGAN",
    "DINAS PERINDUSTRIAN DAN PERDAGANGAN",
    "DINAS PERTANIAN DAN PERKEBUNAN",
    "DINAS PERUMAHAN RAKYAT DAN KAWASAN PERMUKIMAN",
    "DINAS PETERNAKAN DAN KESEHATAN HEWAN",
    "DINAS SOSIAL",
    "DINAS TENAGA KERJA DAN TRANSMIGRASI",
    "GUBERNUR JAWA TENGAH",
    "INSPEKTORAT",
    "KOMISI IRIGASI PROVINSI JAWA TENGAH",
    "KOMITE OLAHRAGA NASIONAL INDONESIA PROVINSI JAWA TENGAH",
    "RUMAH SAKIT JIWA DAERAH AMINO GONDOHUTOMO",
    "RUMAH SAKIT JIWA DAERAH Dr. AMINO GONDOHUTOMO",
    "RUMAH SAKIT JIWA DAERAH Dr. ARIF ZAINUDIN",
    "RUMAH SAKIT JIWA DAERAH DR. RM. SOEDJARWADI",
    "RUMAH SAKIT UMUM DAERAH dr. ADHYATMA, MPH",
    "RUMAH SAKIT UMUM DAERAH PROF. Dr. MARGONO SOEKARJO",
    "RUMAH SAKIT UMUM DAERAH Dr. REHATTA",
    "KOMISI IRIGASI PROVINSI JAWA TENGAH",
    "TESTING DEV"
];
opdList.sort();
const selectOpd = document.getElementById("opd");

opdList.forEach(opd => {
    const option = document.createElement("option");
    option.value = opd;
    option.text = opd;
    selectOpd.appendChild(option);
});
